
import { RecordType, ServiceRecord } from './types';
import { excelSerialToDate, getWeekDay } from './utils/dataUtils';

const rawData = [
  "Claudemir,Compra disco Shopee,Serviços,52,45866,segunda-feira,claudemir,Evandro,Maringá",
  "Claudemir,Arrunar Comporta prélimpeza,Serviços,200,45866,segunda-feira,Altair,Evandro,Maringá",
  "Claudemir,Abastecimento gol,Serviços,150,45866,segunda-feira,Posto Volpato,Evandro,Maringá",
  "Claudemir,Montar Balança Anderson,Serviços,200,45868,quarta-feira,Pratic,Evandro,Maringá",
  "Claudemir,Pintar Espositor/Reformar e pintar espositor,Serviços,200,45869,quinta-feira,Pratic,Evandro,Maringá",
  "Claudemir,Substituir rampa de carregamento N9,Serviços,200,45870,sexta-feira,Atacado,Evandro,Maringá",
  "Claudemir,Compra Eixo e bucha Ferro Velho,Serviços,97.5,45870,sexta-feira,Itaipu Ferragens,Evandro,Maringá",
  "Claudemir,Colocar grade no compartimento do comprensor,Serviços,200,45873,segunda-feira,Domingos,Evandro,Maringá",
  "Claudemir,Substituir Eixo de articulação da rampa No 8,Serviços,200,45874,terça-feira,Atacado,Evandro,Maringá",
  "Claudemir,Abastecimento gol,Serviços,150,45874,terça-feira,claudemir,Evandro,Maringá",
  "Claudemir,Compra Eixo e bucha Ferro Velho,Serviços,189,45874,terça-feira,Itaipu Ferragens,Evandro,Maringá",
  "Claudemir,Soldar protecção rampas /Desamasar Alinhar Rampa n4,Serviços,200,45875,quarta-feira,Atacado,Evandro,Maringá",
  "Claudemir,Pagamento Despesas,Pagamentos,800,45875,quarta-feira,claudemir,Evandro,Maringá",
  "Claudemir,Reformar e pintar expositores quatro pecas,Serviços,200,45876,quinta-feira,Pratic,Evandro,Maringá",
  "Claudemir,Revisar e engraxar todos os mancais rosca palha,Serviços,200,45877,sexta-feira,Altair,Evandro,Maringá",
  "Claudemir,Desmontar grades cesta basica,Serviços,200,45880,segunda-feira,Atacado,Evandro,Maringá",
  "Claudemir,Abastecimento gol,Serviços,150,45880,segunda-feira,Posto Volpato,Evandro,Maringá",
  "Claudemir,Fazer carinho para caixa de pao,Serviços,200,45881,terça-feira,Vitor,Evandro,Maringá",
  "Claudemir,Fazer carinho para caixa de pao,Serviços,200,45882,quarta-feira,Vitor,Evandro,Maringá",
  "Claudemir,Fazer Treliça e fachamento barracão,Serviços,225,45883,quinta-feira,laurindo,Claudemir/Evandro,Corumbatai do sul",
  "Claudemir,Fazer Treliça e fachamento barracão,Serviços,225,45884,sexta-feira,laurindo,Claudemir/Evandro,Corumbatai do sul",
  "Claudemir,Fazer Treliça e fachamento barracão,Serviços,225,45885,sábado,laurindo,Claudemir/Evandro,Corumbatai do sul",
  "Claudemir,Fazer Treliça e fachamento barracão,Serviços,225,45887,segunda-feira,laurindo,Claudemir/Evandro,Corumbatai do sul",
  "Claudemir,Compra Tinta inga tintas,Serviços,83.7,45887,segunda-feira,Ingá Tintas,Claudemir/Evandro,Maringá",
  "Claudemir,Trocar Dobradica Rampa n.o 2 Atacado,Serviços,200,45888,terça-feira,Atacado,Claudemir/Evandro,Maringá",
  "Claudemir,Montar Grade cesta basica atacado / Tarde,Serviços,200,45889,quarta-feira,Atacado,Claudemir/Evandro,Maringá",
  "Claudemir,Abastecimento gol,Serviços,100,45889,quarta-feira,Posto Bac Americano,Claudemir/Evandro,Maringá",
  "Claudemir,Entelhar grade Cesta Basica,Serviços,200,45890,quinta-feira,Atacado,Claudemir/Evandro,Maringá",
  "Claudemir,Pagamento Diárias,Pagamentos,2000,45890,quinta-feira,claudemir,Claudemir/Evandro,Maringá",
  "Claudemir,Montagem Equipamentos,Serviços,225,45894,segunda-feira,Norberto,Claudemir/Evandro,Guarapuava",
  "Claudemir,Montagem Equipamentos,Serviços,225,45895,terça-feira,Norberto,Claudemir/Evandro,Guarapuava",
  "Claudemir,Montagem Equipamentos,Serviços,225,45896,quarta-feira,Norberto,Claudemir/Evandro,Guarapuava",
  "Claudemir,Montagem Equipamentos,Serviços,225,45897,quinta-feira,Norberto,Claudemir/Evandro,Guarapuava",
  "Claudemir,Montagem Equipamentos,Serviços,225,45898,sexta-feira,Norberto,Claudemir/Evandro,Guarapuava",
  "Claudemir,Montagem Equipamentos,Serviços,225,45901,segunda-feira,Norberto,Claudemir/Evandro,Guarapuava",
  "Claudemir,Montagem Equipamentos,Serviços,225,45902,terça-feira,Norberto,Claudemir/Evandro,Guarapuava",
  "Claudemir,Pagamento Despesas Janta,Serviços,47,45902,terça-feira,claudemir,Claudemir/Evandro,Guarapuava",
  "Claudemir,Montagem Equipamentos,Serviços,225,45903,quarta-feira,Norberto,Claudemir/Evandro,Guarapuava",
  "Claudemir,Montagem Equipamentos,Serviços,225,45904,quinta-feira,Norberto,Claudemir/Evandro,Guarapuava",
  "Claudemir,Montagem Equipamentos,Serviços,225,45905,sexta-feira,Norberto,Claudemir/Evandro,Guarapuava",
  "Claudemir,Montagem Equipamentos,Serviços,225,45908,segunda-feira,Norberto,Claudemir/Evandro,Guarapuava",
  "Claudemir,Montagem Equipamentos,Serviços,225,45909,terça-feira,Norberto,Claudemir/Evandro,Guarapuava",
  "Claudemir,Montagem Equipamentos,Serviços,225,45910,quarta-feira,Norberto,Claudemir/Evandro,Guarapuava",
  "Claudemir,Montagem Equipamentos,Serviços,225,45911,quinta-feira,Norberto,Claudemir/Evandro,Guarapuava",
  "Claudemir,Montagem Equipamentos,Serviços,225,45912,sexta-feira,Norberto,Claudemir/Evandro,Guarapuava",
  "Claudemir,Pagamento Diárias Guarapuava,Pagamentos,3375,45914,domingo,Norberto,Claudemir/Evandro,Guarapuava",
  "Claudemir,Pargamento Diárias Claudemir,Pagamentos,375,45914,domingo,claudemir,Claudemir/Evandro,Maringá",
  "Claudemir,Montar cilo Eletronica Elevador,Serviços,200,45915,segunda-feira,Altair,Claudemir/Evandro,Maringá",
  "Claudemir,Abastecimento gol,Serviços,100,45909,terça-feira,Posto Volpato,Claudemir/Evandro,Maringá",
  "Claudemir,Montar cilo Eletronica Elevador,Serviços,200,45916,terça-feira,Altair,Claudemir/Evandro,Maringá",
  "Claudemir,Montar cilo Eletronica Elevador,Serviços,200,45917,quarta-feira,Altair,Claudemir/Evandro,Maringá",
  "Claudemir,Desmontar paineis VITOR,Serviços,200,45918,quinta-feira,Vitor,Claudemir/Evandro,Maringá",
  "Claudemir,Desmontar paineis VITOR,Serviços,200,45919,sexta-feira,Vitor,Claudemir/Evandro,Maringá",
  "Claudemir,Montar cilo Eletronica Elevador,Serviços,200,45922,segunda-feira,Altair,Claudemir/Evandro,Maringá",
  "Claudemir,Montar cilo Eletronica Elevador,Serviços,200,45923,terça-feira,Altair,Claudemir/Evandro,Maringá",
  "Claudemir,Montar cilo Eletronica Elevador,Serviços,200,45924,quarta-feira,Altair,Claudemir/Evandro,Maringá",
  "Claudemir,Montar cilo Eletronica Elevador,Serviços,200,45925,quinta-feira,Altair,Claudemir/Evandro,Maringá",
  "Claudemir,Compra Rebit casa dos Parafusos,Serviços,69,45925,quinta-feira,Casa Dos Paraf,Claudemir/Evandro,Maringá",
  "Claudemir,Montar Camera Fria,Serviços,200,45926,sexta-feira,Vitor,Claudemir/Evandro,Maringá",
  "Claudemir,Montar Camera Fria,Serviços,200,45927,sábado,Vitor,Claudemir/Evandro,Maringá",
  "Claudemir,Montar Camara Producao,Serviços,200,45929,segunda-feira,Vitor,Claudemir/Evandro,Maringá",
  "Claudemir,Montar Camara Producao,Serviços,200,45930,terça-feira,Vitor,Claudemir/Evandro,Maringá",
  "Claudemir,Abastecimento gol,Serviços,100,45914,domingo,Posto Volpato,Claudemir/Evandro,Maringá",
  "Claudemir,Montar Camara Producao,Serviços,200,45931,quarta-feira,Vitor,Claudemir/Evandro,Maringá",
  "Claudemir,Montar Camara Producao,Serviços,200,45932,quinta-feira,Vitor,Claudemir/Evandro,Maringá",
  "Claudemir,Montar Camara Producao,Serviços,200,45933,sexta-feira,Vitor,Claudemir/Evandro,Maringá",
  "Claudemir,Pagamentos,Pagamentos,2000,45935,domingo,claudemir,Claudemir/Evandro,Maringá",
  "Claudemir,Acabamento Camara Producao,Serviços,200,45936,segunda-feira,Vitor,Evandro,Maringá",
  "Claudemir,Acabamento Camara Producao,Serviços,200,45937,terça-feira,Vitor,Evandro,Maringá",
  "Claudemir,Abastecimento gol,Serviços,100,45930,terça-feira,Posto Volpato,Claudemir/Evandro,Maringá",
  "Claudemir,Desmontar Camera Fria,Serviços,200,45938,quarta-feira,Vitor,Evandro/Eleandro,Maringá",
  "Claudemir,Trocar tela peneira pre-limpeza 01 /02,Serviços,200,45939,quinta-feira,Gean,Evandro/Eleandro,Maringá",
  "Claudemir,Casa dos Parafusos,Serviços,67.3,45939,quinta-feira,Gean,Evandro/Eleandro,Maringá",
  "Claudemir,Trocar tela cata pedra,Serviços,100,45940,sexta-feira,Gean,Evandro/Eleandro,Maringá",
  "Claudemir,Trocar tela cata pedra,Serviços,45,45940,sexta-feira,GI Ferragens,Evandro/Eleandro,Maringá",
  "Claudemir,Abastecimento gol,Serviços,100,45937,terça-feira,Posto Volpato,Claudemir,Maringá",
  "Claudemir,Retirada e instalação Eletronica Selecionadora,Serviços,200,45943,segunda-feira,Gean,Evandro/Eleandro,Maringá",
  "Claudemir,Retirada e instalação Eletronica Selecionadora,Serviços,200,45944,terça-feira,Gean,Evandro/Eleandro,Maringá",
  "Claudemir,Retirada e instalação Eletronica Selecionadora,Serviços,200,45945,quarta-feira,Gean,Evandro/Eleandro,Maringá",
  "Claudemir,Abastecimento gol,Serviços,100,45945,quarta-feira,Posto Volpato,Claudemir,Maringá",
  "Claudemir,Retirada e instalação Eletronica Selecionadora,Serviços,200,45946,quinta-feira,Gean,Evandro/Eleandro,Maringá",
  "Claudemir,Retirada e instalação Eletronica Selecionadora,Serviços,200,45947,sexta-feira,Gean,Evandro/Eleandro,Maringá",
  "Claudemir,Retirada e instalação Eletronica Selecionadora,Serviços,200,45950,segunda-feira,Gean,Evandro/Eleandro,Maringá",
  "Claudemir,Pagamentos diárias,Pagamentos,1500,45950,segunda-feira,claudemir,Evandro,Maringá",
  "Claudemir,Abastecimento gol,Serviços,150,45950,segunda-feira,Posto Volpato,Claudemir,Maringá",
  "Claudemir,Retirada e instalação Eletronica Peneira,Serviços,200,45951,terça-feira,Gean,Evandro/Eleandro,Maringá",
  "Claudemir,Retirada e instalação Eletronica Peneira,Serviços,200,45952,quarta-feira,Gean,Evandro/Eleandro,Maringá",
  "Claudemir,Retirada e instalação Eletronica Peneira,Serviços,200,45953,quinta-feira,Gean,Evandro/Eleandro,Maringá",
  "Claudemir,Compra veda rosca,Serviços,15,45953,quinta-feira,GI Ferragens,Evandro/Eleandro,Maringá",
  "Claudemir,Retirada e instalação Eletronica Fazer Cilo,Serviços,200,45954,sexta-feira,Gean,Evandro/Eleandro,Maringá",
  "Claudemir,Pagamentos diárias,Pagamentos,1500,45956,domingo,claudemir,Evandro,Maringá",
  "Claudemir,Abastecimento gol,Serviços,100,45960,quinta-feira,Posto Volpato,Claudemir,Maringá",
  "Claudemir,Retirada e instalação Eletronica Peneira,Serviços,200,45957,segunda-feira,Gean,Evandro,Maringá",
  "Claudemir,Retirada e instalação Eletronica Fazer Cilo,Serviços,200,45958,terça-feira,Gean,Evandro,Maringá",
  "Claudemir,Fazer cilo repase,Serviços,200,45959,quarta-feira,Gean,Evandro,Maringá",
  "Claudemir,Fazer cilo repase,Serviços,200,45960,quinta-feira,Gean,Evandro,Maringá",
  "Claudemir,Fazer cilo repase,Serviços,200,45961,sexta-feira,Gean,Evandro,Maringá",
  "Claudemir,fazer bica cilo repasse,Serviços,200,45964,segunda-feira,Gean,Evandro/Eleandro,Maringá",
  "Claudemir,Abastecimento gol,Serviços,100,45964,segunda-feira,Posto Volpato,Claudemir,Maringá",
  "Claudemir,Montar Iso Painel Produção,Serviços,200,45965,terça-feira,Vitor,Evandro/Eleandro,Maringá",
  "Claudemir,Montar Iso Painel Produção,Serviços,200,45966,quarta-feira,Vitor,Evandro/Eleandro,Maringá",
  "Claudemir,Montar Iso Painel Produção,Serviços,200,45967,quinta-feira,Vitor,Evandro/Eleandro,Maringá",
  "Claudemir,Montar Iso Painel Produção,Serviços,200,45968,sexta-feira,Vitor,Evandro/Eleandro,Maringá",
  "Claudemir,Pagamentos diárias,Pagamentos,2300,45970,domingo,claudemir,Evandro,Maringá",
  "Claudemir,Montar Iso Painel Produção,Serviços,200,45971,segunda-feira,Vitor,Evandro/Eleandro,Maringá",
  "Claudemir,Abastecimento gol,Serviços,150,45971,segunda-feira,Posto Volpato,Claudemir,Maringá",
  "Claudemir,Montar Iso Painel Produção,Serviços,200,45972,terça-feira,Vitor,Evandro/Eleandro,Maringá",
  "Claudemir,Montar Iso Painel Produção,Serviços,200,45973,quarta-feira,Vitor,Evandro/Eleandro,Maringá",
  "Claudemir,Montar eltronica Nova,Serviços,200,45974,quinta-feira,Altair,Evandro/Claudemir,Maringá",
  "Claudemir,Troca Homocinética Gol,Serviços,323,45975,sexta-feira,claudemir,Evandro/Claudemir,Maringá",
  "Claudemir,Pagamentos diárias,Pagamentos,1200,45976,sábado,claudemir,Evandro,Maringá",
  "Claudemir,Reformar pintar elevadores,Serviços,200,45978,segunda-feira,claudemir,Evadro/Eleandro,Maringá",
  "Claudemir,Reformar pintar elevadores,Serviços,200,45979,terça-feira,claudemir,Evadro/Eleandro,Maringá",
  "Claudemir,Reformar pintar elevadores,Serviços,200,45980,quarta-feira,claudemir,Evadro/Eleandro,Maringá",
  "Claudemir,Abastecimento gol,Serviços,150,45980,quarta-feira,Posto Volpato,Claudemir,Maringá",
  "Claudemir,Montar Elevador Residuo,Serviços,200,45981,quinta-feira,Altair,Evandro/Claudemir,Maringá",
  "Claudemir,Fechamento telha,Serviços,200,45981,quinta-feira,Atacado,Evandro/Claudemir,Maringá",
  "Claudemir,Montar elevador de Residuo Eletónica,Serviços,200,45985,segunda-feira,Rm Alimentos,Evandro/Eleandro,paiçandu",
  "Claudemir,Montar elevador de Residuo Eletónica,Serviços,200,45986,terça-feira,Rm Alimentos,Evandro/Eleandro,paiçandu",
  "Claudemir,Pagamentos diárias,Pagamentos,300,45986,terça-feira,claudemir,Evandro,Maringá",
  "Claudemir,Abastecimento gol,Serviços,100,45986,terça-feira,Posto Volpato,Evandro/Eleandro,Maringá",
  "Claudemir,Retirar aumeto caçamba fazer escadas,Serviços,200,45987,quarta-feira,Luiz Palha,Evandro/Eleandro,Maringá",
  "Claudemir,Retirar aumeto caçamba fazer escadas,Serviços,200,45988,quinta-feira,Luiz Palha,Evandro/Eleandro,Maringá",
  "Claudemir,Colocar canos elevador Eletronica,Serviços,200,45989,sexta-feira,Altair,Evandro/Eleandro,Maringá",
  "Claudemir,Desmontar Eletronica desativada,Serviços,200,45992,segunda-feira,Altair,Evandro/Eleandro,Maringá",
  "Claudemir,Pagamento Diárias,Pagamentos,2000,45992,segunda-feira,claudemir,Evandro,Maringá",
  "Claudemir,Abastecimento gol,Serviços,100,45992,segunda-feira,Posto Volpato,Evandro/Eleandro,Maringá",
  "Claudemir,Desmontar Elevador desativado,Serviços,200,45993,terça-feira,Altair,Evandro/Eleandro,Maringá",
  "Claudemir,Impermeabilizaçao cilo esterno/Limpeza,Serviços,200,45994,quarta-feira,Altair,Evandro/Eleandro,Maringá",
  "Claudemir,Impermeabilizaçao cilo esterno/Limpeza,Serviços,200,45995,quinta-feira,Altair,Evandro/Eleandro,Maringá",
  "Claudemir,Impermeabilizaçao cilo esterno/Limpeza,Serviços,200,45996,sexta-feira,Altair,Evandro/Eleandro,Maringá",
  "Claudemir,Pagamento Diárias,Pagamentos,1000,45996,sexta-feira,claudemir,Evandro,Maringá",
  "Claudemir,Montando estufa crescimento / Impermeabilizacao Cilo,Serviços,200,45999,segunda-feira,Junior,Evandro/Eleandro,Maringá",
  "Claudemir,Manutenção Rsca da palha troca elicoide,Serviços,200,46000,terça-feira,Altair,Evandro/Claudemir,Maringá",
  "Claudemir,Montando Valvula para elevador/Impermeabilização Cilo,Serviços,200,46001,quarta-feira,Rm Alimentos,Evandro/Eleandro,Maringá",
  "Claudemir,Abastecimento gol,Serviços,100,46001,quarta-feira,Claudemir,Evandro,Maringá",
  "Claudemir,Trocar canecas de elevador /Tirar Canecas de correia,Serviços,200,46002,quinta-feira,Arroz grego,Evandro/Eleandro,Maringá",
  "Claudemir,Arrumar Rosca Alex/Montar Valvulas Feijão/PInt Exposi,Serviços,200,46002,quinta-feira,Rm Alimentos,Evandro/Eleandro,Maringá",
  "Claudemir,Abastecimento gol /Cartao Leandro,Serviços,150,46003,sexta-feira,Posto Parque,Evandro/Eleandro,Maringá",
  "Claudemir,Manutenção Gol Alinhamento/Amortexedor,Serviços,302,46004,sábado,Passarela,Evandro/Eleandro,Maringá",
  "Claudemir,Fabricar peneira feijao /Troca elicoide rosca/vedacao,Serviços,200,46006,segunda-feira,Rm Alimentos,Evandro/Eleandro,Maringá",
  "Claudemir,Fabricar peneira feijao,Serviços,200,46007,terça-feira,Rm Alimentos,Evandro/Eleandro,Maringá",
  "Claudemir,Fabricar peneira feijao /Grade Laurindo,Serviços,200,46008,quarta-feira,laurindo,Evandro/Eleandro,Maringá",
  "Claudemir,Fabricar peneira feijao /Grade Laurindo/Piso Clarice,Serviços,200,46009,quinta-feira,laurindo,Evandro/Eleandro,Maringá",
  "Claudemir,Fabricar peneira feijao /Montar grade Laurindo,Serviços,200,46010,sexta-feira,laurindo,Evandro/Eleandro,Maringá"
];

export const INITIAL_RECORDS: ServiceRecord[] = rawData.map((row, index) => {
  const [worker, desc, typeStr, val, serial, day, client, exec, city] = row.split(',');
  const dateIso = excelSerialToDate(parseInt(serial));
  
  return {
    id: `rec_${index}_${Date.now()}`,
    workerName: worker,
    description: desc,
    type: typeStr === 'Serviços' ? RecordType.SERVICOS : RecordType.PAGAMENTOS,
    value: parseFloat(val),
    date: dateIso,
    weekDay: day,
    client: client,
    executedBy: exec,
    city: city
  };
});
